<?php

/**
 * Implementation of hook_menu().
 */
function activeadmin_menu() {
  $items = array();
  $items['aa/nodetitle/edit'] = array(
    'title' => 'Tartalom cím szerkesztése',
    'page callback' => 'activeadmin_nodetitle',
    'access callback' => 'user_access',
    'access arguments' => 'access administration pages',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Grab new node title and node id from AJAX POST and save.
 *
 * @todo
 *   This just replaces the title of the current revision,
 *   but we really should create a new revision instead.
 *   Which should also fire nodeapi!
 */
function activeadmin_nodetitle() {
  $title = $_POST['title'];
  $nid = str_replace('node-title-', '', $_POST['node']);
  $vid = db_fetch_object(db_query('SELECT vid FROM {node} WHERE nid = %d', $nid));
  db_query("UPDATE {node_revisions} SET title = '%s' WHERE nid = %d and vid = %d", $title, $nid, $vid->vid);
  db_query("UPDATE {node} SET title = '%s' WHERE nid = %d", $title, $nid);
  $title = db_fetch_object(db_query('SELECT title FROM {node} WHERE nid = %d', $nid));
  print $title->title;
}
