<?php

/**
 * Implementation of hook_menu()
 */
function pages_menu() {
  $items = array();
  $pages = array(
    // HTML files
    'weblabor/impresszum'        => array('impresszum',      'Impresszum'), 
    'weblabor/joginyilatkozat'   => array('joginyilatkozat', 'Jogi nyilatkozat'),
    'weblabor/adatvedelem'       => array('adatvedelem',     'Adatvédelem'),
    'weblabor/rolunk'            => array('rolunk',          'Rólunk'),
    'weblabor/publikalas'        => array('publikalas',      'Publikálás a Weblaboron'),
    // TODO: anonim bekuldes?!
    'weblabor/segitseg'          => array('segitseg',        'Segítség'),
    'weblabor/mediaajanlat'      => array('mediaajanlat',    'Médiaajánlat'),
    // TODO: update az uj webcimekre
    'bekuldes'                   => array('bekuldes',        'Tartalom beküldése'),
    'weblabor/404'               => array('404',             'Nem található'),
    'weblabor/403'               => array('403',             'Elérés megtagadva'),
    'kereses'                    => array('kereses',         'Részletes keresés'),
    // Dynamic pages
    // TODO: update az uj webcimekre
    'weblabor/terkep'            => array('_sitemap',        'Webhely térkép'),
    'rss'                        => array('_feed_all',       'RSS csatornák'),
  );
  foreach ($pages as $path => $params) {
    if (strpos($params[0], '_') === 0) {
      $items[$path] = array(
        'title'           => $params[1],
        'page callback'   => '_pages'. $params[0],
        'access callback' => TRUE,
        'type'            => MENU_CALLBACK,
        'file'            => 'pages.inc',
      );
    }
    else {
      $items[$path] = array(
        'title'           => $params[1],
        'page callback'   => 'file_get_contents',
        'page arguments'  => array('sites/all/modules/pages/'. $params[0] .'.html'),
        'access callback' => TRUE,
        'type'            => MENU_CALLBACK,
      );
    }
  }
  $items['nodesbytype/%'] = array(
    'title'           => 'Tartalmak',
    'page callback'   => '_pages_nodes_bytype',
    'page arguments'  => array(1, FALSE),
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK,
    'file'            => 'pages.inc',
  );
  $items['nodesbytype/feed/%'] = array(
    'title'           => 'Tartalmak',
    'page callback'   => '_pages_nodes_bytype',
    'page arguments'  => array(2, TRUE),
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK,
    'file'            => 'pages.inc',
  );
  $items['crss/nodetype/%'] = array(
    'title'           => 'Hozzászólások',
    'page callback'   => '_pages_comment_feed_bytype',
    'page arguments'  => array(2),
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK,
    'file'            => 'pages.inc',
  );

  // Cikkek
  $items['cikkek'] = array(
    'title'           => 'Cikkek',
    'page callback'   => '_pages_nodes_bytype',
    'page arguments'  => array('article'),
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK,
    'file'            => 'pages.inc',
  );
  $items['cikkek/attekintes'] = array(
    'title'           => 'Áttekintés',
    'type'            => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['cikkek/bekuldes'] = array(
    'title'            => 'Beküldés',
    'page callback'    => 'pages_add_node_page',
    'page arguments'   => array('article'),
    'access callback'  => 'user_access',
    'access arguments' => array('create article content'),
    'type'             => MENU_LOCAL_TASK,
  );

  // Blog
  $items['blog'] = array(
    'title'           => 'Blog',
    'page callback'   => '_pages_nodes_bytype',
    'page arguments'  => array('blogpost'),
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK,
    'file'            => 'pages.inc',
  );
  $items['blog/attekintes'] = array(
    'title'           => 'Áttekintés',
    'type'            => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['blog/bekuldes'] = array(
    'title'            => 'Beküldés',
    'page callback'    => 'pages_add_node_page',
    'page arguments'   => array('blogpost'),
    'access callback'  => 'user_access',
    'access arguments' => array('create blogpost content'),
    'type'             => MENU_LOCAL_TASK,
  );

  // Szavazások
  $items['szavazasok'] = array(
    'title'           => 'Szavazások',
    'page callback'   => '_pages_nodes_bytype',
    'page arguments'  => array('poll'),
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK,
    'file'            => 'pages.inc',
  );
  $items['szavazasok/attekintes'] = array(
    'title'           => 'Áttekintés',
    'type'            => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['szavazasok/bekuldes'] = array(
    'title'            => 'Beküldés',
    'page callback'    => 'pages_add_node_page',
    'page arguments'   => array('poll'),
    'access callback'  => 'user_access',
    'access arguments' => array('create poll content'),
    'type'             => MENU_LOCAL_TASK,
  );

  // Fórum
  $items['forumok'] = array(
    'title'            => 'Fórumok',
    'page callback'    => 'pages_forum_page',
    'access arguments' => array('access content'),
    'type'             => MENU_SUGGESTED_ITEM,
  );
  $items['forumok/attekintes'] = array(
    'title'           => 'Áttekintés',
    'type'            => MENU_DEFAULT_LOCAL_TASK,
    'weight'          => -10,
  );
  $items['forumok/idoszerint'] = array(
    'title'           => 'Időrendben',
    'page callback'   => '_pages_nodes_bytype',
    'page arguments'  => array('forum'),
    'access callback' => TRUE,
    'type'            => MENU_LOCAL_TASK,
    'file'            => 'pages.inc',
    'weight'          => 10,
  );
  $items['forumok/bekuldes'] = array(
    'title'            => 'Beküldés',
    'page callback'    => 'pages_add_node_page',
    'page arguments'   => array('forum'),
    'access callback'  => 'user_access',
    'access arguments' => array('create forum topics'),
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 20,
  );
  $items['forum/%'] = array(
    'title' => 'Forums',
    'page callback' => 'pages_forum_page',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );
  $items['forum/%/attekitntes'] = array(
    'title'           => 'Áttekintés',
    'type'            => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['forum/%/bekuldes'] = array(
    'title'            => 'Beküldés',
    'page callback'    => 'pages_add_node_page',
    'page arguments'   => array('forum', 1),
    'access callback'  => 'user_access',
    'access arguments' => array('create forum topics'),
    'type'             => MENU_LOCAL_TASK,
  );

  /*$forum_types[$type] = array(
    'title' => t('Post new @node_type', array('@node_type' => node_get_types('name', $type))),
    'href' => 'node/add/'. str_replace('_', '-', $type) .'/'. $variables['tid']
  );*/

  return $items;
}

function pages_init() {
  if ($_GET['q'] == 'forumok') {
    drupal_add_feed(url("nodesbytype/feed/forum", array('absolute' => TRUE)), 'RSS - Fórumok');
  }
}

/**
 * Proxy függvény a node form hívásához. (A menu API 'file' csak lokális.)
 */
function pages_add_node_page($type, $extra = NULL) {
  include_once drupal_get_path('module', 'node') .'/node.pages.inc';
  return node_add($type, $extra);
}

/**
 * Proxy függvény a forum oldal hívásához. (A menu API 'file' csak lokális.)
 */
function pages_forum_page($tid = 0) {
  include_once drupal_get_path('module', 'forum') .'/forum.pages.inc';
  return forum_page($tid);
}

/**
 * Implementation of hook_block()
 */
function pages_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      return array('search' => array('info' => 'Keresés'));
    case 'view':
      return array('subject' => 'Keresés', 'content' => '
  <div id="searchbox">
   <form method="get" action="http://www.google.com/search"><div class="clear-block">
    <input type="hidden" name="ie" value="UTF-8" />
    <input type="hidden" name="oe" value="UTF-8" />
    <input type="hidden" name="domains" value="weblabor.hu" />
    <input type="hidden" name="sitesearch" value="weblabor.hu" />
    <input type="text" class="form-text" name="q" size="20" maxlength="255" value="" />
    <a href="/kereses">Részletes</a>
    <input type="submit" class="form-submit" name="btnG" value="Keresés" /></div>
   </form>
  </div>');
  }
}

/**
 * Teaser mindig kerüljön be a body-ba.
 */
function pages_form_alter(&$form, $form_state, $form_id) {
  if (in_array($form_id, array('forum_node_form', 'job_node_form', 'blogpost_node_form', 'article_node_form', 'bookreview_node_form'))) {
    $form['#validate'][] = 'pages_node_form_validate';
  }
}

function pages_node_form_validate($form, &$form_state) {
  if (!$form_state['values']['teaser_include']) {
    form_set_error('teaser_include', 'A bevezető a törzs első része kell legyen.');
  }
}
